name: LogicLikeRN0_76 (Detox + Jest Android CI)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/lib/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "emulator"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Android Debug and Test APKs
        run: cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

      - name: Run Jest tests
        run: npm run test
