name: LogicLikeRN0_76 (Detox + Jest Android CI)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
      ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
      PATH: ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK environment variable
        run: echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          rm sdk-tools.zip

      - name: Accept Android SDK licenses
        run: yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "emulator"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci

      - name: Build Android Debug APK and Test APK
        run: cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

      - name: Run Jest tests
        run: npm run test

      - name: Run Detox tests (Debug)
        run: npm run e2e:android:debug
