name: LogicLikeRN0_76 (Detox + Jest Android CI)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: react-native-community/setup-android@v2
        with:
          api-levels: 34
          build-tools: 34.0.0
          ndk-version: 27.1.12297006

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Android Debug and Test APKs
        run: cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

      - name: Run Jest tests
        run: npm run test

      - name: Run Detox tests
        run: npm run detox:test:android
